name: "js tests"


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        run: npm test
