name: "eslint"


on: [push]

jobs:
    eslint:
        name: runner / eslint
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - uses: actions/setup-node@v2
            with:
              node-version: 19

          - name: Install dependencies
            run: npm i --force  # OR: yarn 

          - name: Install other deps
            run: npm install --force --save-dev eslint-plugin-n@latest 
            
          - name: Run eslint on changed files
            uses: tj-actions/eslint-changed-files@v20
            with:
              config_path: ".eslintrc.yml"
              fail_on_error: false
              file_extensions: |
                **/*.ts
                **/*.tsx
